### ISSUE TITLE
ModuleNotFoundError: No module named 'nyuv2.raw.project'

### ISSUE THREAD

**Issue by Christon-Ragavan** [GabrielMajeri/nyuv2-python-toolbox#1]
when I run the test file I get this error,
ModuleNotFoundError: No module named 'nyuv2.raw.project'

what should project file contain. I feel lost without documentation. it would help me if you give me some guidance in this.
Thank you

**Comment by GabrielMajeri** [comment]
Hello,
This project is still a WIP and I removed that module because the projection code was buggy. I've pushed a new commit to master and it should work now.
