### ISSUE TITLE
Project depth onto RGB

### ISSUE THREAD

**Issue by jungerm2** [GabrielMajeri/nyuv2-python-toolbox#2]
Hello, your python port has been very useful so far. I was wondering if you ever implemented the part that processes the raw data, specifically projecting the raw depth values onto the rgb image. Basically what is left out here:

https://github.com/GabrielMajeri/nyuv2-python-toolbox/blob/1ad502ca083fd81f908ffe28daab814a7fa724ce/test.py#L62

Is there any progress on this? How did you overcome this? 
Thanks in advance.

**Comment by GabrielMajeri** [comment]
Yes, the function for projecting the depth values into world space exists:

https://github.com/GabrielMajeri/nyuv2-python-toolbox/blob/1ad502ca083fd81f908ffe28daab814a7fa724ce/nyuv2/raw/project.py#L6

What I haven't gotten around to implementing was applying lens correction to the color image. You will get a reasonable depth map, but it's got some imprecisions here and there.

Unfortunately, the code for performing the actual correction is quite math heavy and I haven't been successful at porting it.

**Comment by jungerm2** [comment]
I was referring to the lens correction portion. I might take a crack at it and fork off. Thanks!

**Comment by Tord-Zhang** [comment]
@GabrielMajeri @jungerm2 Hi， I have met the same problem since I am not able to use matlab. Have you reimplement the projection in python?
