### ISSUE TITLE
Incorrect frame sync

### ISSUE THREAD

**Issue by jungerm2** [GabrielMajeri/nyuv2-python-toolbox#3]
The frame synchronization method is missing a *very* important line, you need to add:

```
diff = new_diff
```
somewhere after the if, around here:

https://github.com/GabrielMajeri/nyuv2-python-toolbox/blob/1ad502ca083fd81f908ffe28daab814a7fa724ce/nyuv2/raw/extract.py#L87

Otherwise, the timedelta never gets updated.

**Comment by GabrielMajeri** [comment]
Thanks for the correction!
