### ISSUE TITLE
generate RGB images

### ISSUE THREAD

**Issue by robo-alex** [GabrielMajeri/nyuv2-python-toolbox#5]
Hi! Thanks for your contributions!
Would you please tell me how to generate synchronized RGB and Depth frames by this toolbox, corresponding to the `get_synched_frames.m` from the original one?

**Comment by GabrielMajeri** [comment]
Hello! The [`raw/extract.py` module](https://github.com/GabrielMajeri/nyuv2-python-toolbox/blob/9394c589416b744a5b812d4b8535e286787f2073/nyuv2/raw/extract.py) is what you're probably looking for.

Do note that the port of the original Matlab toolbox isn't 100% complete, so some features might be missing.
